### ISSUE TITLE
docker-compose能否加一个使用远程mysql版本

### ISSUE THREAD

**Issue by taiyi747** [snailyp/gemini-balance#75]
docker-compose能否加一个使用远程mysql版本
我想部署在容器云，但是重启清空mysql
以后更新不好搞

**Comment by taiyi747** [comment]
> 你按README文档配置好数据库的环境变量说可以了。
> 
> 配置项	说明	默认值
> **数据库配置**		
> `MYSQL_HOST`	必填，MySQL 数据库主机地址	`localhost`
> `MYSQL_PORT`	必填，MySQL 数据库端口	`3306`
> `MYSQL_USER`	必填，MySQL 数据库用户名	`your_db_user`
> `MYSQL_PASSWORD`	必填，MySQL 数据库密码	`your_db_password`
> `MYSQL_DATABASE`	必填，MySQL 数据库名称	`defaultdb`

不行的，docker-compose里没办法先配置.env

**Comment by BigUncle** [comment]
> > 你按README文档配置好数据库的环境变量说可以了。
> > 
> > 配置项	说明	默认值
> > **数据库配置**		
> > `MYSQL_HOST`	必填，MySQL 数据库主机地址	`localhost`
> > `MYSQL_PORT`	必填，MySQL 数据库端口	`3306`
> > `MYSQL_USER`	必填，MySQL 数据库用户名	`your_db_user`
> > `MYSQL_PASSWORD`	必填，MySQL 数据库密码	`your_db_password`
> > `MYSQL_DATABASE`	必填，MySQL 数据库名称	`defaultdb`
> 
> 不行的，docker-compose里没办法先配置.env

你是不是想把项目部署在hugging face的space？
把`.env.example`里的每个参数都手工加到space的环境变量里，私密变量放在secret variance里。

**Comment by taiyi747** [comment]
> > > 你按README文档配置好数据库的环境变量说可以了。
> > > 配置项	说明	默认值
> > > **数据库配置**
> > > `MYSQL_HOST`	必填，MySQL 数据库主机地址	`localhost`
> > > `MYSQL_PORT`	必填，MySQL 数据库端口	`3306`
> > > `MYSQL_USER`	必填，MySQL 数据库用户名	`your_db_user`
> > > `MYSQL_PASSWORD`	必填，MySQL 数据库密码	`your_db_password`
> > > `MYSQL_DATABASE`	必填，MySQL 数据库名称	`defaultdb`
> > 
> > 
> > 不行的，docker-compose里没办法先配置.env
> 
> 你是不是想把项目部署在hugging face的space？ 把`.env.example`里的每个参数都手工加到space的环境变量里，私密变量放在secret variance里。

不是的，一些容器平台不支持放文件的，只支持环境变量environment，主要是作者这个docker-compose是内置MySQL，不支持远程吧。。

**Comment by BigUncle** [comment]
> > > > 你按README文档配置好数据库的环境变量说可以了。
> > > > 配置项	说明	默认值
> > > > **数据库配置**
> > > > `MYSQL_HOST`	必填，MySQL 数据库主机地址	`localhost`
> > > > `MYSQL_PORT`	必填，MySQL 数据库端口	`3306`
> > > > `MYSQL_USER`	必填，MySQL 数据库用户名	`your_db_user`
> > > > `MYSQL_PASSWORD`	必填，MySQL 数据库密码	`your_db_password`
> > > > `MYSQL_DATABASE`	必填，MySQL 数据库名称	`defaultdb`
> > > 
> > > 
> > > 不行的，docker-compose里没办法先配置.env
> > 
> > 
> > 你是不是想把项目部署在hugging face的space？ 把`.env.example`里的每个参数都手工加到space的环境变量里，私密变量放在secret variance里。
> 
> 不是的，一些容器平台不支持放文件的，只支持环境变量environment，主要是作者这个docker-compose是内置MySQL，不支持远程吧。。

我说的就是直接在容器里设置变量，不需要.env文件。
关键点前面已经说了，具体的建议你搜索下教程吧。

**Comment by taiyi747** [comment]
我感觉你没明白我的意思，我问的是能不能远程mysql

**Comment by BigUncle** [comment]
https://gb-docs.snaily.top/guide/setup-hf.html

**Comment by taiyi747** [comment]
> https://gb-docs.snaily.top/guide/setup-hf.html

我觉得你可能没有理解我的意思
而且你大概率只用Hugging Face不用其他家比如aws，Vercel，koyeb所以没什么聊下去必要了

**Comment by yanhao98** [comment]
```yaml
services:
  gemini-balance:
    image: ghcr.io/snailyp/gemini-balance:latest
    container_name: gemini-balance
    environment:
      - MYSQL_HOST=mysql.host.com
      - MYSQL_PORT=3306
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_DATABASE=mysql_database
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; exit(0) if requests.get('http://localhost:8000/health').status_code == 200 else exit(1)\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
```

```shell
docker run --name gemini-balance \
  -e MYSQL_HOST=mysql.host.com \
  -e MYSQL_PORT=3306 \
  -e MYSQL_USER=mysql_user \
  -e MYSQL_PASSWORD=mysql_password \
  -e MYSQL_DATABASE=mysql_database \
  --restart unless-stopped \
  -p 8000:8000 \
  ghcr.io/snailyp/gemini-balance:latest

```
